.TH "" "" "" "" ""
.SH yaml2resume
.RS
.PP
No name given yet
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ yaml2resume
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ yaml2resume\ [\ \-t\ TEMPLATE\ ]\ [\ \-l\ ]
\ \ \ \ yaml2resume\ list
\ \ \ \ yaml2resume\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ yaml2resume
\ \ \ \ \-t,\ \-\-template\ TEMPLATE\ \ \ \ \ template\ file\ to\ use\ \ \ \ \ (\ \[aq]latex\-jr\[aq]\ )
\ \ \ \ \-l,\ \-\-latex\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ compile\ the\ output\ with\ `xelatex`.

Commands:
\ \ \ \ list\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ list\ current\ templates

Arguments:
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
