.TH "" "" "" "" ""
.SH yaml2resume
.RS
.PP
No name given yet
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ yaml2resume
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ yaml2resume\ [\ \-t\ TEMPLATE\ ]\ [\ \-l\ ]\ [\ \-j\ ]
\ \ \ \ yaml2resume\ list
\ \ \ \ yaml2resume\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ yaml2resume
\ \ \ \ \-t,\ \-\-template\ TEMPLATE\ \ \ \ \ template\ file\ to\ use\ \ \ \ \ (\ \[aq]latex\-jr\[aq]\ )
\ \ \ \ \-l,\ \-\-latex\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ compile\ the\ output\ with\ `xelatex`.
\ \ \ \ \-j,\ \-\-json\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ interpret\ input\ data\ as\ valid\ json

Commands:
\ \ \ \ list\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ list\ current\ templates

Description:
\ \ \ \ This\ command\ expands\ a\ liquid\ template\ (file\ TEMPLATE)\ by\ using
\ \ \ \ either\ valid\ YAML\ or\ JSON\ read\ from\ stdin.

\ \ \ \ Note:\ if\ TEMPLATE\ starts\ with\ `.`\ or\ `/`\ it\ is\ interpreted
\ \ \ \ as\ an\ absolute\ file\ instead\ of\ the\ name\ of\ built\-in\ plugin.
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH New features
.IP \[bu] 2
add missing package \-\- Feb 25th
16 (../../commit/d5120c1f4dfff9bce2d9624df62a617b12166ccc)
.IP \[bu] 2
add json input and absolute template filenames \-\- Jan 1st
16 (../../commit/5160a04c4a910820a0ccf8cf7378a5209d62ac13)
